name: publish package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm test
      - run: npm run build:prod
      - run: cd dist/opentelemetry-interceptor && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
